// Package models contains the types for schema 'AllergyNew'.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
	"errors"
	"time"

	"github.com/go-sql-driver/mysql"
)

// MqTestTemplate represents a row from 'AllergyNew.mq_test_templates'.
type MqTestTemplate struct {
	ID         uint           `json:"id"`          // id
	PracticeID sql.NullInt64  `json:"practice_id"` // practice_id
	LocationID sql.NullInt64  `json:"location_id"` // location_id
	Name       sql.NullString `json:"name"`        // name
	CreatorID  sql.NullInt64  `json:"creator_id"`  // creator_id
	CreateDate mysql.NullTime `json:"create_date"` // create_date
	Active     int8           `json:"active"`      // active
	UpdatedBy  sql.NullInt64  `json:"updated_by"`  // updated_by
	Updated    time.Time      `json:"updated"`     // updated

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the MqTestTemplate exists in the database.
func (mtt *MqTestTemplate) Exists() bool {
	return mtt._exists
}

// Deleted provides information if the MqTestTemplate has been deleted from the database.
func (mtt *MqTestTemplate) Deleted() bool {
	return mtt._deleted
}

// Insert inserts the MqTestTemplate to the database.
func (mtt *MqTestTemplate) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if mtt._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key provided by autoincrement
	const sqlstr = `INSERT INTO AllergyNew.mq_test_templates (` +
		`practice_id, location_id, name, creator_id, create_date, active, updated_by, updated` +
		`) VALUES (` +
		`?, ?, ?, ?, ?, ?, ?, ?` +
		`)`

	// run query
	XOLog(sqlstr, mtt.PracticeID, mtt.LocationID, mtt.Name, mtt.CreatorID, mtt.CreateDate, mtt.Active, mtt.UpdatedBy, mtt.Updated)
	res, err := db.Exec(sqlstr, mtt.PracticeID, mtt.LocationID, mtt.Name, mtt.CreatorID, mtt.CreateDate, mtt.Active, mtt.UpdatedBy, mtt.Updated)
	if err != nil {
		return err
	}

	// retrieve id
	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	// set primary key and existence
	mtt.ID = uint(id)
	mtt._exists = true

	return nil
}

// Update updates the MqTestTemplate in the database.
func (mtt *MqTestTemplate) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !mtt._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if mtt._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE AllergyNew.mq_test_templates SET ` +
		`practice_id = ?, location_id = ?, name = ?, creator_id = ?, create_date = ?, active = ?, updated_by = ?, updated = ?` +
		` WHERE id = ?`

	// run query
	XOLog(sqlstr, mtt.PracticeID, mtt.LocationID, mtt.Name, mtt.CreatorID, mtt.CreateDate, mtt.Active, mtt.UpdatedBy, mtt.Updated, mtt.ID)
	_, err = db.Exec(sqlstr, mtt.PracticeID, mtt.LocationID, mtt.Name, mtt.CreatorID, mtt.CreateDate, mtt.Active, mtt.UpdatedBy, mtt.Updated, mtt.ID)
	return err
}

// Save saves the MqTestTemplate to the database.
func (mtt *MqTestTemplate) Save(db XODB) error {
	if mtt.Exists() {
		return mtt.Update(db)
	}

	return mtt.Insert(db)
}

// Delete deletes the MqTestTemplate from the database.
func (mtt *MqTestTemplate) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !mtt._exists {
		return nil
	}

	// if deleted, bail
	if mtt._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM AllergyNew.mq_test_templates WHERE id = ?`

	// run query
	XOLog(sqlstr, mtt.ID)
	_, err = db.Exec(sqlstr, mtt.ID)
	if err != nil {
		return err
	}

	// set deleted
	mtt._deleted = true

	return nil
}

// UserByCreatorID returns the User associated with the MqTestTemplate's CreatorID (creator_id).
//
// Generated from foreign key 'mq_test_templates_creator'.
func (mtt *MqTestTemplate) UserByCreatorID(db XODB) (*User, error) {
	return UserByID(db, uint(mtt.CreatorID.Int64))
}

// PracticeLocation returns the PracticeLocation associated with the MqTestTemplate's LocationID (location_id).
//
// Generated from foreign key 'mq_test_templates_location'.
func (mtt *MqTestTemplate) PracticeLocation(db XODB) (*PracticeLocation, error) {
	return PracticeLocationByID(db, uint(mtt.LocationID.Int64))
}

// Practice returns the Practice associated with the MqTestTemplate's PracticeID (practice_id).
//
// Generated from foreign key 'mq_test_templates_practice'.
func (mtt *MqTestTemplate) Practice(db XODB) (*Practice, error) {
	return PracticeByID(db, uint(mtt.PracticeID.Int64))
}

// UserByUpdatedBy returns the User associated with the MqTestTemplate's UpdatedBy (updated_by).
//
// Generated from foreign key 'mq_test_templates_updated'.
func (mtt *MqTestTemplate) UserByUpdatedBy(db XODB) (*User, error) {
	return UserByID(db, uint(mtt.UpdatedBy.Int64))
}

// MqTestTemplatesByLocationID retrieves a row from 'AllergyNew.mq_test_templates' as a MqTestTemplate.
//
// Generated from index 'Locations'.
func MqTestTemplatesByLocationID(db XODB, locationID sql.NullInt64) ([]*MqTestTemplate, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, practice_id, location_id, name, creator_id, create_date, active, updated_by, updated ` +
		`FROM AllergyNew.mq_test_templates ` +
		`WHERE location_id = ?`

	// run query
	XOLog(sqlstr, locationID)
	q, err := db.Query(sqlstr, locationID)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*MqTestTemplate{}
	for q.Next() {
		mtt := MqTestTemplate{
			_exists: true,
		}

		// scan
		err = q.Scan(&mtt.ID, &mtt.PracticeID, &mtt.LocationID, &mtt.Name, &mtt.CreatorID, &mtt.CreateDate, &mtt.Active, &mtt.UpdatedBy, &mtt.Updated)
		if err != nil {
			return nil, err
		}

		res = append(res, &mtt)
	}

	return res, nil
}

// MqTestTemplatesByPracticeID retrieves a row from 'AllergyNew.mq_test_templates' as a MqTestTemplate.
//
// Generated from index 'Practices'.
func MqTestTemplatesByPracticeID(db XODB, practiceID sql.NullInt64) ([]*MqTestTemplate, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, practice_id, location_id, name, creator_id, create_date, active, updated_by, updated ` +
		`FROM AllergyNew.mq_test_templates ` +
		`WHERE practice_id = ?`

	// run query
	XOLog(sqlstr, practiceID)
	q, err := db.Query(sqlstr, practiceID)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*MqTestTemplate{}
	for q.Next() {
		mtt := MqTestTemplate{
			_exists: true,
		}

		// scan
		err = q.Scan(&mtt.ID, &mtt.PracticeID, &mtt.LocationID, &mtt.Name, &mtt.CreatorID, &mtt.CreateDate, &mtt.Active, &mtt.UpdatedBy, &mtt.Updated)
		if err != nil {
			return nil, err
		}

		res = append(res, &mtt)
	}

	return res, nil
}

// MqTestTemplatesByCreatorID retrieves a row from 'AllergyNew.mq_test_templates' as a MqTestTemplate.
//
// Generated from index 'mq_test_templates_creator'.
func MqTestTemplatesByCreatorID(db XODB, creatorID sql.NullInt64) ([]*MqTestTemplate, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, practice_id, location_id, name, creator_id, create_date, active, updated_by, updated ` +
		`FROM AllergyNew.mq_test_templates ` +
		`WHERE creator_id = ?`

	// run query
	XOLog(sqlstr, creatorID)
	q, err := db.Query(sqlstr, creatorID)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*MqTestTemplate{}
	for q.Next() {
		mtt := MqTestTemplate{
			_exists: true,
		}

		// scan
		err = q.Scan(&mtt.ID, &mtt.PracticeID, &mtt.LocationID, &mtt.Name, &mtt.CreatorID, &mtt.CreateDate, &mtt.Active, &mtt.UpdatedBy, &mtt.Updated)
		if err != nil {
			return nil, err
		}

		res = append(res, &mtt)
	}

	return res, nil
}

// MqTestTemplateByID retrieves a row from 'AllergyNew.mq_test_templates' as a MqTestTemplate.
//
// Generated from index 'mq_test_templates_id_pkey'.
func MqTestTemplateByID(db XODB, id uint) (*MqTestTemplate, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, practice_id, location_id, name, creator_id, create_date, active, updated_by, updated ` +
		`FROM AllergyNew.mq_test_templates ` +
		`WHERE id = ?`

	// run query
	XOLog(sqlstr, id)
	mtt := MqTestTemplate{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, id).Scan(&mtt.ID, &mtt.PracticeID, &mtt.LocationID, &mtt.Name, &mtt.CreatorID, &mtt.CreateDate, &mtt.Active, &mtt.UpdatedBy, &mtt.Updated)
	if err != nil {
		return nil, err
	}

	return &mtt, nil
}

// MqTestTemplatesByUpdatedBy retrieves a row from 'AllergyNew.mq_test_templates' as a MqTestTemplate.
//
// Generated from index 'mq_test_templates_updated'.
func MqTestTemplatesByUpdatedBy(db XODB, updatedBy sql.NullInt64) ([]*MqTestTemplate, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, practice_id, location_id, name, creator_id, create_date, active, updated_by, updated ` +
		`FROM AllergyNew.mq_test_templates ` +
		`WHERE updated_by = ?`

	// run query
	XOLog(sqlstr, updatedBy)
	q, err := db.Query(sqlstr, updatedBy)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*MqTestTemplate{}
	for q.Next() {
		mtt := MqTestTemplate{
			_exists: true,
		}

		// scan
		err = q.Scan(&mtt.ID, &mtt.PracticeID, &mtt.LocationID, &mtt.Name, &mtt.CreatorID, &mtt.CreateDate, &mtt.Active, &mtt.UpdatedBy, &mtt.Updated)
		if err != nil {
			return nil, err
		}

		res = append(res, &mtt)
	}

	return res, nil
}
