// Package models contains the types for schema 'AllergyNew'.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
	"errors"
	"time"
)

// MqTestTemplatesAntigensName represents a row from 'AllergyNew.mq_test_templates_antigens_names'.
type MqTestTemplatesAntigensName struct {
	ID        uint           `json:"id"`         // id
	AntigenID sql.NullInt64  `json:"antigen_id"` // antigen_id
	Name      sql.NullString `json:"name"`       // name
	UpdatedBy sql.NullInt64  `json:"updated_by"` // updated_by
	Updated   time.Time      `json:"updated"`    // updated

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the MqTestTemplatesAntigensName exists in the database.
func (mttan *MqTestTemplatesAntigensName) Exists() bool {
	return mttan._exists
}

// Deleted provides information if the MqTestTemplatesAntigensName has been deleted from the database.
func (mttan *MqTestTemplatesAntigensName) Deleted() bool {
	return mttan._deleted
}

// Insert inserts the MqTestTemplatesAntigensName to the database.
func (mttan *MqTestTemplatesAntigensName) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if mttan._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key provided by autoincrement
	const sqlstr = `INSERT INTO AllergyNew.mq_test_templates_antigens_names (` +
		`antigen_id, name, updated_by, updated` +
		`) VALUES (` +
		`?, ?, ?, ?` +
		`)`

	// run query
	XOLog(sqlstr, mttan.AntigenID, mttan.Name, mttan.UpdatedBy, mttan.Updated)
	res, err := db.Exec(sqlstr, mttan.AntigenID, mttan.Name, mttan.UpdatedBy, mttan.Updated)
	if err != nil {
		return err
	}

	// retrieve id
	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	// set primary key and existence
	mttan.ID = uint(id)
	mttan._exists = true

	return nil
}

// Update updates the MqTestTemplatesAntigensName in the database.
func (mttan *MqTestTemplatesAntigensName) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !mttan._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if mttan._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE AllergyNew.mq_test_templates_antigens_names SET ` +
		`antigen_id = ?, name = ?, updated_by = ?, updated = ?` +
		` WHERE id = ?`

	// run query
	XOLog(sqlstr, mttan.AntigenID, mttan.Name, mttan.UpdatedBy, mttan.Updated, mttan.ID)
	_, err = db.Exec(sqlstr, mttan.AntigenID, mttan.Name, mttan.UpdatedBy, mttan.Updated, mttan.ID)
	return err
}

// Save saves the MqTestTemplatesAntigensName to the database.
func (mttan *MqTestTemplatesAntigensName) Save(db XODB) error {
	if mttan.Exists() {
		return mttan.Update(db)
	}

	return mttan.Insert(db)
}

// Delete deletes the MqTestTemplatesAntigensName from the database.
func (mttan *MqTestTemplatesAntigensName) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !mttan._exists {
		return nil
	}

	// if deleted, bail
	if mttan._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM AllergyNew.mq_test_templates_antigens_names WHERE id = ?`

	// run query
	XOLog(sqlstr, mttan.ID)
	_, err = db.Exec(sqlstr, mttan.ID)
	if err != nil {
		return err
	}

	// set deleted
	mttan._deleted = true

	return nil
}

// MqTestTemplatesAntigensNamesByAntigenID retrieves a row from 'AllergyNew.mq_test_templates_antigens_names' as a MqTestTemplatesAntigensName.
//
// Generated from index 'Antigens'.
func MqTestTemplatesAntigensNamesByAntigenID(db XODB, antigenID sql.NullInt64) ([]*MqTestTemplatesAntigensName, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, antigen_id, name, updated_by, updated ` +
		`FROM AllergyNew.mq_test_templates_antigens_names ` +
		`WHERE antigen_id = ?`

	// run query
	XOLog(sqlstr, antigenID)
	q, err := db.Query(sqlstr, antigenID)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*MqTestTemplatesAntigensName{}
	for q.Next() {
		mttan := MqTestTemplatesAntigensName{
			_exists: true,
		}

		// scan
		err = q.Scan(&mttan.ID, &mttan.AntigenID, &mttan.Name, &mttan.UpdatedBy, &mttan.Updated)
		if err != nil {
			return nil, err
		}

		res = append(res, &mttan)
	}

	return res, nil
}

// MqTestTemplatesAntigensNameByID retrieves a row from 'AllergyNew.mq_test_templates_antigens_names' as a MqTestTemplatesAntigensName.
//
// Generated from index 'mq_test_templates_antigens_names_id_pkey'.
func MqTestTemplatesAntigensNameByID(db XODB, id uint) (*MqTestTemplatesAntigensName, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, antigen_id, name, updated_by, updated ` +
		`FROM AllergyNew.mq_test_templates_antigens_names ` +
		`WHERE id = ?`

	// run query
	XOLog(sqlstr, id)
	mttan := MqTestTemplatesAntigensName{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, id).Scan(&mttan.ID, &mttan.AntigenID, &mttan.Name, &mttan.UpdatedBy, &mttan.Updated)
	if err != nil {
		return nil, err
	}

	return &mttan, nil
}
