// Package models contains the types for schema 'AllergyNew'.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
	"errors"
	"time"
)

// VialRequestsHolding represents a row from 'AllergyNew.vial_requests_holding'.
type VialRequestsHolding struct {
	ID                uint           `json:"id"`                 // id
	RequestID         uint           `json:"request_id"`         // request_id
	PatientID         uint           `json:"patient_id"`         // patient_id
	PracticeID        uint           `json:"practice_id"`        // practice_id
	LocationID        uint           `json:"location_id"`        // location_id
	FormulaID         uint           `json:"formula_id"`         // formula_id
	Verified          bool           `json:"verified"`           // verified
	RequestDate       time.Time      `json:"request_date"`       // request_date
	Priority          bool           `json:"priority"`           // priority
	HoldReason        sql.NullString `json:"hold_reason"`        // hold_reason
	PatientFirstname  sql.NullString `json:"patient_firstname"`  // patient_firstname
	PatientMiddlename sql.NullString `json:"patient_middlename"` // patient_middlename
	PatientLastname   sql.NullString `json:"patient_lastname"`   // patient_lastname
	IntakeMethod      string         `json:"intake_method"`      // intake_method
	ShotLocation      sql.NullString `json:"shot_location"`      // shot_location
	PracticeName      sql.NullString `json:"practice_name"`      // practice_name
	LocationName      sql.NullString `json:"location_name"`      // location_name
	UserFirstname     sql.NullString `json:"user_firstname"`     // user_firstname
	UserMiddlename    sql.NullString `json:"user_middlename"`    // user_middlename
	UserLastname      sql.NullString `json:"user_lastname"`      // user_lastname
	UpdatedBy         sql.NullInt64  `json:"updated_by"`         // updated_by
	Updated           time.Time      `json:"updated"`            // updated

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the VialRequestsHolding exists in the database.
func (vrh *VialRequestsHolding) Exists() bool {
	return vrh._exists
}

// Deleted provides information if the VialRequestsHolding has been deleted from the database.
func (vrh *VialRequestsHolding) Deleted() bool {
	return vrh._deleted
}

// Insert inserts the VialRequestsHolding to the database.
func (vrh *VialRequestsHolding) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if vrh._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key provided by autoincrement
	const sqlstr = `INSERT INTO AllergyNew.vial_requests_holding (` +
		`request_id, patient_id, practice_id, location_id, formula_id, verified, request_date, priority, hold_reason, patient_firstname, patient_middlename, patient_lastname, intake_method, shot_location, practice_name, location_name, user_firstname, user_middlename, user_lastname, updated_by, updated` +
		`) VALUES (` +
		`?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?` +
		`)`

	// run query
	XOLog(sqlstr, vrh.RequestID, vrh.PatientID, vrh.PracticeID, vrh.LocationID, vrh.FormulaID, vrh.Verified, vrh.RequestDate, vrh.Priority, vrh.HoldReason, vrh.PatientFirstname, vrh.PatientMiddlename, vrh.PatientLastname, vrh.IntakeMethod, vrh.ShotLocation, vrh.PracticeName, vrh.LocationName, vrh.UserFirstname, vrh.UserMiddlename, vrh.UserLastname, vrh.UpdatedBy, vrh.Updated)
	res, err := db.Exec(sqlstr, vrh.RequestID, vrh.PatientID, vrh.PracticeID, vrh.LocationID, vrh.FormulaID, vrh.Verified, vrh.RequestDate, vrh.Priority, vrh.HoldReason, vrh.PatientFirstname, vrh.PatientMiddlename, vrh.PatientLastname, vrh.IntakeMethod, vrh.ShotLocation, vrh.PracticeName, vrh.LocationName, vrh.UserFirstname, vrh.UserMiddlename, vrh.UserLastname, vrh.UpdatedBy, vrh.Updated)
	if err != nil {
		return err
	}

	// retrieve id
	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	// set primary key and existence
	vrh.ID = uint(id)
	vrh._exists = true

	return nil
}

// Update updates the VialRequestsHolding in the database.
func (vrh *VialRequestsHolding) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !vrh._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if vrh._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE AllergyNew.vial_requests_holding SET ` +
		`request_id = ?, patient_id = ?, practice_id = ?, location_id = ?, formula_id = ?, verified = ?, request_date = ?, priority = ?, hold_reason = ?, patient_firstname = ?, patient_middlename = ?, patient_lastname = ?, intake_method = ?, shot_location = ?, practice_name = ?, location_name = ?, user_firstname = ?, user_middlename = ?, user_lastname = ?, updated_by = ?, updated = ?` +
		` WHERE id = ?`

	// run query
	XOLog(sqlstr, vrh.RequestID, vrh.PatientID, vrh.PracticeID, vrh.LocationID, vrh.FormulaID, vrh.Verified, vrh.RequestDate, vrh.Priority, vrh.HoldReason, vrh.PatientFirstname, vrh.PatientMiddlename, vrh.PatientLastname, vrh.IntakeMethod, vrh.ShotLocation, vrh.PracticeName, vrh.LocationName, vrh.UserFirstname, vrh.UserMiddlename, vrh.UserLastname, vrh.UpdatedBy, vrh.Updated, vrh.ID)
	_, err = db.Exec(sqlstr, vrh.RequestID, vrh.PatientID, vrh.PracticeID, vrh.LocationID, vrh.FormulaID, vrh.Verified, vrh.RequestDate, vrh.Priority, vrh.HoldReason, vrh.PatientFirstname, vrh.PatientMiddlename, vrh.PatientLastname, vrh.IntakeMethod, vrh.ShotLocation, vrh.PracticeName, vrh.LocationName, vrh.UserFirstname, vrh.UserMiddlename, vrh.UserLastname, vrh.UpdatedBy, vrh.Updated, vrh.ID)
	return err
}

// Save saves the VialRequestsHolding to the database.
func (vrh *VialRequestsHolding) Save(db XODB) error {
	if vrh.Exists() {
		return vrh.Update(db)
	}

	return vrh.Insert(db)
}

// Delete deletes the VialRequestsHolding from the database.
func (vrh *VialRequestsHolding) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !vrh._exists {
		return nil
	}

	// if deleted, bail
	if vrh._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM AllergyNew.vial_requests_holding WHERE id = ?`

	// run query
	XOLog(sqlstr, vrh.ID)
	_, err = db.Exec(sqlstr, vrh.ID)
	if err != nil {
		return err
	}

	// set deleted
	vrh._deleted = true

	return nil
}

// VialRequestsHoldingsByLocationID retrieves a row from 'AllergyNew.vial_requests_holding' as a VialRequestsHolding.
//
// Generated from index 'Locations'.
func VialRequestsHoldingsByLocationID(db XODB, locationID uint) ([]*VialRequestsHolding, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, request_id, patient_id, practice_id, location_id, formula_id, verified, request_date, priority, hold_reason, patient_firstname, patient_middlename, patient_lastname, intake_method, shot_location, practice_name, location_name, user_firstname, user_middlename, user_lastname, updated_by, updated ` +
		`FROM AllergyNew.vial_requests_holding ` +
		`WHERE location_id = ?`

	// run query
	XOLog(sqlstr, locationID)
	q, err := db.Query(sqlstr, locationID)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*VialRequestsHolding{}
	for q.Next() {
		vrh := VialRequestsHolding{
			_exists: true,
		}

		// scan
		err = q.Scan(&vrh.ID, &vrh.RequestID, &vrh.PatientID, &vrh.PracticeID, &vrh.LocationID, &vrh.FormulaID, &vrh.Verified, &vrh.RequestDate, &vrh.Priority, &vrh.HoldReason, &vrh.PatientFirstname, &vrh.PatientMiddlename, &vrh.PatientLastname, &vrh.IntakeMethod, &vrh.ShotLocation, &vrh.PracticeName, &vrh.LocationName, &vrh.UserFirstname, &vrh.UserMiddlename, &vrh.UserLastname, &vrh.UpdatedBy, &vrh.Updated)
		if err != nil {
			return nil, err
		}

		res = append(res, &vrh)
	}

	return res, nil
}

// VialRequestsHoldingsByPatientID retrieves a row from 'AllergyNew.vial_requests_holding' as a VialRequestsHolding.
//
// Generated from index 'Patients'.
func VialRequestsHoldingsByPatientID(db XODB, patientID uint) ([]*VialRequestsHolding, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, request_id, patient_id, practice_id, location_id, formula_id, verified, request_date, priority, hold_reason, patient_firstname, patient_middlename, patient_lastname, intake_method, shot_location, practice_name, location_name, user_firstname, user_middlename, user_lastname, updated_by, updated ` +
		`FROM AllergyNew.vial_requests_holding ` +
		`WHERE patient_id = ?`

	// run query
	XOLog(sqlstr, patientID)
	q, err := db.Query(sqlstr, patientID)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*VialRequestsHolding{}
	for q.Next() {
		vrh := VialRequestsHolding{
			_exists: true,
		}

		// scan
		err = q.Scan(&vrh.ID, &vrh.RequestID, &vrh.PatientID, &vrh.PracticeID, &vrh.LocationID, &vrh.FormulaID, &vrh.Verified, &vrh.RequestDate, &vrh.Priority, &vrh.HoldReason, &vrh.PatientFirstname, &vrh.PatientMiddlename, &vrh.PatientLastname, &vrh.IntakeMethod, &vrh.ShotLocation, &vrh.PracticeName, &vrh.LocationName, &vrh.UserFirstname, &vrh.UserMiddlename, &vrh.UserLastname, &vrh.UpdatedBy, &vrh.Updated)
		if err != nil {
			return nil, err
		}

		res = append(res, &vrh)
	}

	return res, nil
}

// VialRequestsHoldingsByPracticeID retrieves a row from 'AllergyNew.vial_requests_holding' as a VialRequestsHolding.
//
// Generated from index 'Practices'.
func VialRequestsHoldingsByPracticeID(db XODB, practiceID uint) ([]*VialRequestsHolding, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, request_id, patient_id, practice_id, location_id, formula_id, verified, request_date, priority, hold_reason, patient_firstname, patient_middlename, patient_lastname, intake_method, shot_location, practice_name, location_name, user_firstname, user_middlename, user_lastname, updated_by, updated ` +
		`FROM AllergyNew.vial_requests_holding ` +
		`WHERE practice_id = ?`

	// run query
	XOLog(sqlstr, practiceID)
	q, err := db.Query(sqlstr, practiceID)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*VialRequestsHolding{}
	for q.Next() {
		vrh := VialRequestsHolding{
			_exists: true,
		}

		// scan
		err = q.Scan(&vrh.ID, &vrh.RequestID, &vrh.PatientID, &vrh.PracticeID, &vrh.LocationID, &vrh.FormulaID, &vrh.Verified, &vrh.RequestDate, &vrh.Priority, &vrh.HoldReason, &vrh.PatientFirstname, &vrh.PatientMiddlename, &vrh.PatientLastname, &vrh.IntakeMethod, &vrh.ShotLocation, &vrh.PracticeName, &vrh.LocationName, &vrh.UserFirstname, &vrh.UserMiddlename, &vrh.UserLastname, &vrh.UpdatedBy, &vrh.Updated)
		if err != nil {
			return nil, err
		}

		res = append(res, &vrh)
	}

	return res, nil
}

// VialRequestsHoldingsByPriority retrieves a row from 'AllergyNew.vial_requests_holding' as a VialRequestsHolding.
//
// Generated from index 'Priority'.
func VialRequestsHoldingsByPriority(db XODB, priority bool) ([]*VialRequestsHolding, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, request_id, patient_id, practice_id, location_id, formula_id, verified, request_date, priority, hold_reason, patient_firstname, patient_middlename, patient_lastname, intake_method, shot_location, practice_name, location_name, user_firstname, user_middlename, user_lastname, updated_by, updated ` +
		`FROM AllergyNew.vial_requests_holding ` +
		`WHERE priority = ?`

	// run query
	XOLog(sqlstr, priority)
	q, err := db.Query(sqlstr, priority)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*VialRequestsHolding{}
	for q.Next() {
		vrh := VialRequestsHolding{
			_exists: true,
		}

		// scan
		err = q.Scan(&vrh.ID, &vrh.RequestID, &vrh.PatientID, &vrh.PracticeID, &vrh.LocationID, &vrh.FormulaID, &vrh.Verified, &vrh.RequestDate, &vrh.Priority, &vrh.HoldReason, &vrh.PatientFirstname, &vrh.PatientMiddlename, &vrh.PatientLastname, &vrh.IntakeMethod, &vrh.ShotLocation, &vrh.PracticeName, &vrh.LocationName, &vrh.UserFirstname, &vrh.UserMiddlename, &vrh.UserLastname, &vrh.UpdatedBy, &vrh.Updated)
		if err != nil {
			return nil, err
		}

		res = append(res, &vrh)
	}

	return res, nil
}

// VialRequestsHoldingsByRequestID retrieves a row from 'AllergyNew.vial_requests_holding' as a VialRequestsHolding.
//
// Generated from index 'Requests'.
func VialRequestsHoldingsByRequestID(db XODB, requestID uint) ([]*VialRequestsHolding, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, request_id, patient_id, practice_id, location_id, formula_id, verified, request_date, priority, hold_reason, patient_firstname, patient_middlename, patient_lastname, intake_method, shot_location, practice_name, location_name, user_firstname, user_middlename, user_lastname, updated_by, updated ` +
		`FROM AllergyNew.vial_requests_holding ` +
		`WHERE request_id = ?`

	// run query
	XOLog(sqlstr, requestID)
	q, err := db.Query(sqlstr, requestID)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*VialRequestsHolding{}
	for q.Next() {
		vrh := VialRequestsHolding{
			_exists: true,
		}

		// scan
		err = q.Scan(&vrh.ID, &vrh.RequestID, &vrh.PatientID, &vrh.PracticeID, &vrh.LocationID, &vrh.FormulaID, &vrh.Verified, &vrh.RequestDate, &vrh.Priority, &vrh.HoldReason, &vrh.PatientFirstname, &vrh.PatientMiddlename, &vrh.PatientLastname, &vrh.IntakeMethod, &vrh.ShotLocation, &vrh.PracticeName, &vrh.LocationName, &vrh.UserFirstname, &vrh.UserMiddlename, &vrh.UserLastname, &vrh.UpdatedBy, &vrh.Updated)
		if err != nil {
			return nil, err
		}

		res = append(res, &vrh)
	}

	return res, nil
}

// VialRequestsHoldingByID retrieves a row from 'AllergyNew.vial_requests_holding' as a VialRequestsHolding.
//
// Generated from index 'vial_requests_holding_id_pkey'.
func VialRequestsHoldingByID(db XODB, id uint) (*VialRequestsHolding, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, request_id, patient_id, practice_id, location_id, formula_id, verified, request_date, priority, hold_reason, patient_firstname, patient_middlename, patient_lastname, intake_method, shot_location, practice_name, location_name, user_firstname, user_middlename, user_lastname, updated_by, updated ` +
		`FROM AllergyNew.vial_requests_holding ` +
		`WHERE id = ?`

	// run query
	XOLog(sqlstr, id)
	vrh := VialRequestsHolding{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, id).Scan(&vrh.ID, &vrh.RequestID, &vrh.PatientID, &vrh.PracticeID, &vrh.LocationID, &vrh.FormulaID, &vrh.Verified, &vrh.RequestDate, &vrh.Priority, &vrh.HoldReason, &vrh.PatientFirstname, &vrh.PatientMiddlename, &vrh.PatientLastname, &vrh.IntakeMethod, &vrh.ShotLocation, &vrh.PracticeName, &vrh.LocationName, &vrh.UserFirstname, &vrh.UserMiddlename, &vrh.UserLastname, &vrh.UpdatedBy, &vrh.Updated)
	if err != nil {
		return nil, err
	}

	return &vrh, nil
}
