/* 
 * Uber API
 *
 * Move your app forward with the Uber API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type PriceEstimate struct {

	// Unique identifier representing a specific product for a given latitude & longitude. For example, uberX in San Francisco will have a different product_id than uberX in Los Angeles
	ProductId string `json:"product_id,omitempty"`

	// [ISO 4217](http://en.wikipedia.org/wiki/ISO_4217) currency code.
	CurrencyCode string `json:"currency_code,omitempty"`

	// Display name of product.
	DisplayName string `json:"display_name,omitempty"`

	// Formatted string of estimate in local currency of the start location. Estimate could be a range, a single number (flat rate) or \"Metered\" for TAXI.
	Estimate string `json:"estimate,omitempty"`

	// Lower bound of the estimated price.
	LowEstimate float32 `json:"low_estimate,omitempty"`

	// Upper bound of the estimated price.
	HighEstimate float32 `json:"high_estimate,omitempty"`

	// Expected surge multiplier. Surge is active if surge_multiplier is greater than 1. Price estimate already factors in the surge multiplier.
	SurgeMultiplier float32 `json:"surge_multiplier,omitempty"`
}
