/* 
 * Uber API
 *
 * Move your app forward with the Uber API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type Product struct {

	// Unique identifier representing a specific product for a given latitude & longitude. For example, uberX in San Francisco will have a different product_id than uberX in Los Angeles.
	ProductId string `json:"product_id,omitempty"`

	// Description of product.
	Description string `json:"description,omitempty"`

	// Display name of product.
	DisplayName string `json:"display_name,omitempty"`

	// Capacity of product. For example, 4 people.
	Capacity string `json:"capacity,omitempty"`

	// Image URL representing the product.
	Image string `json:"image,omitempty"`
}
